# Generated by Django 2.0.3 on 2020-04-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200417_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='acionamentos',
            name='modo',
            field=models.CharField(default='Manual', max_length=20),
        ),
    ]
