# Generated by Django 2.0.3 on 2020-04-19 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200419_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acionamentos',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='acionamentos',
            name='idDispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Dispositivos'),
        ),
    ]
