# Generated by Django 2.0.3 on 2020-04-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200419_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivos',
            name='tipo',
            field=models.CharField(default='acionador', max_length=200),
        ),
    ]
