# Generated by Django 2.0.3 on 2020-04-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_dispositivos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='condutividade',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='cronIrrigacao',
            field=models.CharField(default='15 * * * *', max_length=20),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='umidade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='vazao',
            field=models.IntegerField(null=True),
        ),
    ]
