# Generated by Django 2.0.3 on 2020-04-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200419_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
