# Generated by Django 2.0.3 on 2020-04-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_sistema_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertas',
            name='tipo',
            field=models.CharField(default='condutividade', max_length=20),
        ),
        migrations.AlterField(
            model_name='alertas',
            name='idDispositivo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
