# Generated by Django 2.0.3 on 2020-04-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200422_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertas',
            name='limiar',
            field=models.FloatField(null=True),
        ),
    ]
