# Generated by Django 2.0.3 on 2020-05-25 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200422_1715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
    ]
